// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPI3TrcD3Z87ovusL7o4iiBHu9Py1hXf8',
    appId: '1:1030852875003:web:a3a634c1b038bd2df2965e',
    messagingSenderId: '1030852875003',
    projectId: 'authentication-b3762',
    authDomain: 'authentication-b3762.firebaseapp.com',
    storageBucket: 'authentication-b3762.appspot.com',
    measurementId: 'G-KLTSNNM7YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt5ZIcK5bAm3fEcpLfIm4MtNeXLL1azMM',
    appId: '1:1030852875003:android:f4b3eb88be4af4a1f2965e',
    messagingSenderId: '1030852875003',
    projectId: 'authentication-b3762',
    storageBucket: 'authentication-b3762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XWiS2xtxovOHjLlM_oO515VW2AYL4PI',
    appId: '1:1030852875003:ios:0c396eedc3715d4df2965e',
    messagingSenderId: '1030852875003',
    projectId: 'authentication-b3762',
    storageBucket: 'authentication-b3762.appspot.com',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_XWiS2xtxovOHjLlM_oO515VW2AYL4PI',
    appId: '1:1030852875003:ios:0c396eedc3715d4df2965e',
    messagingSenderId: '1030852875003',
    projectId: 'authentication-b3762',
    storageBucket: 'authentication-b3762.appspot.com',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPI3TrcD3Z87ovusL7o4iiBHu9Py1hXf8',
    appId: '1:1030852875003:web:eda65bf08b4e4186f2965e',
    messagingSenderId: '1030852875003',
    projectId: 'authentication-b3762',
    authDomain: 'authentication-b3762.firebaseapp.com',
    storageBucket: 'authentication-b3762.appspot.com',
    measurementId: 'G-KTFTKHR6PZ',
  );
}
